apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-all
  namespace: olatunde-testing
  annotation: 
    argocd.argoproj.io/sync-wave: "-1"
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
