apiVersion: v1
kind: Secret
metadata:
  name: minio-env-configuration
  namespace: aistor
type: Opaque
stringData:
  config.env: |
    export MINIO_ROOT_USER=minio-admin
    export MINIO_ROOT_PASSWORD=alterego22
