apiVersion: local.storage.openshift.io/v1
kind: LocalVolume
metadata:
  name: local-disk
  namespace: openshift-local-storage
spec:
  nodeSelector:
    nodeSelectorTerms:
      - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - crc
  storageClassDevices:
    - storageClassName: lso-sc
      forceWipeDevicesAndDestroyAllData: true     
      volumeMode: Filesystem
      fsType: xfs
      devicePaths:
        - /dev/disk/by-id/virtio-local-disk-01
