#  OADP Secret with MinIO credentials
apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: openshift-adp
  annotations:
    argocd.argoproj.io/sync-wave: "-8"  
stringData:
  cloud: |
    [default]
    aws_access_key_id = admin
    aws_secret_access_key = egoalter

