#  Backup job for olatunde-dev project
apiVersion: velero.io/v1
kind: Backup
metadata:
  name: olatunde-dev-backup
  namespace: openshift-adp
  annotations:
    argocd.argoproj.io/sync-wave: "-8"
spec:
  includedNamespaces:
  - olatunde-dev
  storageLocation: minio-bsl
