# MinIO Deployment 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-server
  namespace: olatunde-storage
  annotations:
    argocd.argoproj.io/sync-wave: "-8"
  label:
    app: minio
spec:
  replicas: 1
  strategy:
    type: Recreate 
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        image: quay.io/minio/minio:latest
        imagePullPolicy: IfNotPresent
        args:
        - server
        - /data
        - --console-address=:9001
        env:
        - name: MINIO_ROOT_USER
          value: admin
        - name: MINIO_ROOT_PASSWORD
          value: egoalter
        ports:
        - containerPort: 9000
          name: s3-api
        - containerPort: 9001
          name: web-ui
        volumeMounts:
        - name: minio-bucket
          mountPath: /data  
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
      volumes:
      - name: minio-bucket
        persistentVolumeClaim:
          claimName: minio-pvc 
          
