#  BackupStorageLocation pointing to MinIO
apiVersion: velero.io/v1
kind: BackupStorageLocation
metadata:
  name: minio-bsl
  namespace: openshift-adp
  annotations:
    argocd.argoproj.io/sync-wave: "-8"
spec:
  provider: aws
  objectStorage:
    bucket: minio-bucket
  config:
    region: minio
    s3ForcePathStyle: "true"
    s3Url: http://minio-service.olatunde-storage.svc.cluster.local:9000
  credential:
    name: minio-secret
    key: cloud
