apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-services
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  project: default
  source:
    repoURL: 'https://github.com/akin-olatunde/openshift-repo.git'
    targetRevision: main
    path: apps/workloads/infra-services
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: openshift-gitops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - SkipDryRunOnMissingResource=true
