apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio-install
  namespace: openshift-gitops
  annotations:
    # WAVE 3: Deploys your actual container environments last once the foundations are secure!
    argocd.argoproj.io/sync-wave: "-6"
spec:
  project: default
  source:
    repoURL: https://github.com/akin-olatunde/openshift-repo.git
    targetRevision: main
    path: apps/workloads
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-gitops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - SkipDryRunOnMissingResource=true
