apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: olatunde-dev
  namespace: openshift-gitops
  argocd.argoproj.io/sync-wave: "-2"
spec:
  project: default
  source:
    repoURL: 'https://github.com/akin-olatunde/openshift-repo.git'
    targetRevision: main
    path: apps/workloads/olatunde-dev
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: olatunde-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false  
