apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
namespace: olatunde-dev
namePrefix: dev-
images:
- name: docker.io/bitnami/nginx:latest  # Looks for this image name coming from the base
#  newName: docker.io/library/nginx:alpine  # Forcefully swaps it out
#  newTag: latest
replicas:
- name: kustom-nginx
  count: 1

