# loki-s3-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: loki-aistor-secret
  namespace: openshift-logging
stringData:
  access_key_id: minio-admin
  access_key_secret: alterego22
  bucketnames: loki
  endpoint: https://aistor-object-store.aistor.svc.cluster.local:9000
  region: us-east-1
  forcepathstyle: "true"
  insecure: "true"
