kind: LokiStack
apiVersion: loki.grafana.com/v1
metadata:
  name: logging-loki
  namespace: openshift-logging
  annotations:
    argocd.argoproj.io/sync-wave: "-6"
spec:
  managementState: Managed
  limits:
    global:
      retention:
        days: 2
  size: 1x.pico
  storage:
    secret:
      type: s3
      name: loki-aistor-secret
    schemas:                                  
    - effectiveDate: "2026-08-13"             
      version: v13
  storageClassName: lso-sc
  tenants:
    mode: openshift-logging
