# MinIO Deployment 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-storage
  namespace: olatunde-storage
  annotations:
    argocd.argoproj.io/sync-wave: "-8"
  label:
    app: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        image: quay.io/minio/minio:latest
        args:
        - server
        - /data
        - --console-address=:9001
        env:
        - name: MINIO_ROOT_USER
          value: admin
        - name: MINIO_ROOT_PASSWORD
          value: egoalter
        ports:
        - containerPort: 9000
        - containerPort: 9001
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%


---
# Minio Service
apiVersion: v1
kind: Service
metadata:
  name: minio-service
  namespace: olatunde-storage
  annotations:
    argocd.argoproj.io/sync-wave: "-8"
spec:
  selector:
    app: minio
  ports:
  - name: api
    port: 9000
    targetPort: 9000
  - name: console
    port: 9001
    targetPort: 9001
  type: ClusterIP


---
#  OADP Secret with MinIO credentials
apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: openshift-adp
  annotations:
    argocd.argoproj.io/sync-wave: "-8"  
stringData:
  cloud: |
    [default]
    aws_access_key_id = admin
    aws_secret_access_key = egoalter



---
#  BackupStorageLocation pointing to MinIO
apiVersion: velero.io/v1
kind: BackupStorageLocation
metadata:
  name: minio-bsl
  namespace: openshift-adp
  annotations:
    argocd.argoproj.io/sync-wave: "-8"
spec:
  provider: aws
  objectStorage:
    bucket: minio-bucket
  config:
    region: minio
    s3ForcePathStyle: "true"
    s3Url: http://minio-service.olatunde-storage.svc.cluster.local:9000
  credential:
    name: minio-secret
    key: cloud


---
#  Backup job for olatunde-dev project
apiVersion: velero.io/v1
kind: Backup
metadata:
  name: olatunde-dev-backup
  namespace: openshift-adp
  annotations:
    argocd.argoproj.io/sync-wave: "-8"
spec:
  includedNamespaces:
  - olatunde-dev
  storageLocation: minio-bsl


---
#  Restore job from backup
apiVersion: velero.io/v1
kind: Restore
metadata:
  name: olatunde-dev-restore
  namespace: openshift-adp
  annotations:
    argocd.argoproj.io/sync-wave: "-8" 
spec:
  backupName: olatunde-dev-backup
