apiVersion: oadp.openshift.io/v1alpha1
kind: DataProtectionApplication
metadata:
  labels:
    app: minio
  name: minio-dpa
  namespace: openshift-adp
  annotations:
    argocd.argoproj.io/sync-wave: "-6"
spec:
  backupLocations:
    - velero:
        config:
          profile: default
          region: minio
          s3ForcePathStyle: 'true'
          s3Url: 'http://minio-service.olatunde-storage.svc.cluster.local:9000'
        credential:
          key: cloud
          name: cloud-credentials
        default: true
        objectStorage:
          bucket: minio-bucket
          prefix: oadp
        provider: aws
  configuration:
    nodeAgent:
      enable: true
      podResources:
        cpuLimit: '1'
        cpuRequest: 50m
        memoryLimit: 1Gi
        memoryRequest: 128Mi
      uploaderType: kopia
    velero:
      defaultPlugins:
        - openshift
        - aws
        - csi
        - kubevirt
        - hypershift
      defaultVolumesToFsBackup: true
      disableFsBackup: false
      restorePVC:
        ignoreDelayBinding: true
  snapshotLocations:
    - velero:
        config:
          profile: default
          region: minio
        provider: aws    
  imagePullPolicy: IfNotPresent

