apiVersion: v1
kind: Secret
metadata:
  name: minio-logging-secret                     
  namespace: openshift-logging                
  annotations:
    argocd.argoproj.io/sync-wave: "-9"
type: Opaque
stringData:
  bucketnames: minio-bucket
  endpoint: http://minio-service.olatunde-storage.svc.cluster.local:9000
  access_key_id: admin
  access_key_secret: egoalter              
  insecure: "true"                          
  region: minio  
  
