apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: nginx-resource-right-sizer
  namespace: openshift-adp
  annotations:
    argocd.argoproj.io/sync-wave: "-6"
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dev-kustom-nginx
  updatePolicy:
    updateMode: "Off"
  resourcePolicy:
    containerPolicies:
    - containerName: '*'
      minAllowed:
        cpu: 50m
        memory: 64Mi
      maxAllowed:
        cpu: 1000m                  
        memory: 2Gi                
